### ISSUE TITLE
Memory leak opening and closing file with osicat-posix:open 

### ISSUE THREAD

**Issue by kayhman** [galdor/osicat#1]
Hi,

I experience memory leaks when opening and closing file with osicat-posix:open, using sbcl 1.2.11

When I run the code below, my sbcl process memory use augments by some hundred MB:

(defun testmemleak ()
  (dotimes (i 10000000)
    (let ((fd (osicat-posix:open "/tmp/memleak" (logior osicat-posix:o-rdwr))))
      (osicat-posix:close fd))))

If I run the same code, but using sb-posix instead of osicat-posix, I don't have the issue.

Regards

**Comment by galdor** [comment]
This is not the official osicat repository. Please submit your bug report on osicat/osicat.

I created the repository before osicat migrated to github, so you cannot see that it is a fork. I do not use it anyway, so I will delete it.

**Comment by kayhman** [comment]
Ok. I've recreated my issue on the good repo :)
